In [3]:
#To apply basic arithmetic operations size of arrays should be same
#This applies the given arithmetic operations elementwise on the arrays
#Operations can also be applied for different sized arrays and is called "Broadcasting" and will be dealt with later

import numpy as np

arr1 = np.array([[1,2,3,4], [5,6,7,8]])
arr2 = np.array([[9,8,7,6], [5,4,3,2]])

In [4]:
#Addition
arr1+arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [5]:
#Subtraction
arr1-arr2

array([[-8, -6, -4, -2],
       [ 0,  2,  4,  6]])

In [6]:
#Multiplication
arr1 * arr2

array([[ 9, 16, 21, 24],
       [25, 24, 21, 16]])

In [7]:
#Division
arr1/arr2

array([[0.11111111, 0.25      , 0.42857143, 0.66666667],
       [1.        , 1.5       , 2.33333333, 4.        ]])

In [8]:
#Exponent
arr1**arr2

array([[   1,  256, 2187, 4096],
       [3125, 1296,  343,   64]], dtype=int32)

In [9]:
#Indexing and Slicing in 1D Array
arr3 = np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr3[5]

5

In [13]:
arr3[5:8]

array([5, 6, 7])

In [14]:
#Initializing all values from 6th to 8th element to 12
arr3[5:8] = 12
arr3

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [15]:
#Initializing can also be performed by changing value in the slice of the original array
arr3_slice = arr3[5:8]
arr3_slice[1] = 54
arr3

array([ 0,  1,  2,  3,  4, 12, 54, 12,  8,  9])

In [16]:
#Indexing and Slicing for Higher Dimensional arrays
arr1_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr1_2d[1]

array([4, 5, 6])

In [21]:
#To access a certain element from a certain row both statements are equivalent
arr1_2d[1][2]
arr1_2d[1,2]

6

In [22]:
arr1_3d = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])
arr1_3d

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [23]:
arr1_3d[1,0,2]

7

In [24]:
arr1_3d[1,0] #Gives all values stored in the 1D array

array([5, 6, 7])

In [25]:
arr1_3d[1] = 5 #Changes all values stored in the 2D array to 5

In [26]:
arr1_3d

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 5, 5],
        [5, 5, 5]]])

In [27]:
#Slicing in higher dimension arrays 
arr1_2d[:2] #Gives first two elements of the given array 

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
#Incase, we want to slice it further, we give a certain slice value which indicates a certain axis
#In above case the slice axis was bydefault 0, thus it showed us all the values
#Suppose we want to get the last two values only of the given slice, then

arr1_2d[:2, 1:] #Gives us the last two elements of the slice containing the first two elements of the array

array([[2, 3],
       [5, 6]])

In [42]:
#The view of the obtained array is the same as the number of dimensions of original array
#To overcome this, we use indexing along with slicing to get the same view as that of the obtained result

arr1_2d[1, 1:]

array([5, 6])

In [44]:
arr1_2d[:, :1] #Gives first elements of every array in given array

array([[1],
       [4],
       [7]])

In [52]:
#Boolean Indexing
#This type of indexing uses the result of a condition to index the ndarray

from numpy.random import randn

letters = np.array(['A','B','C','A','E','D','E','F'])
data = randn(8,2)

In [53]:
letters

array(['A', 'B', 'C', 'A', 'E', 'D', 'E', 'F'], dtype='<U1')

In [49]:
data

array([[-0.27672706, -0.07134891],
       [-0.81256473, -0.80473345],
       [ 0.89644517, -0.41748887],
       [-0.63229649,  0.08291429],
       [-0.99000891, -1.72053271],
       [ 0.29707742,  0.10787855],
       [ 0.58882516, -1.90552738],
       [-0.18391922,  0.52230463]])

In [54]:
#Now we will index the data array and get values only where the letter A occurs
data[letters == 'A']

array([[-0.3441696 ,  1.46550728],
       [ 1.13497238,  1.80359308]])

In [55]:
#Indexing and slicing can be applied to the obtained boolean array
data[letters == 'A', :1]

array([[-0.3441696 ],
       [ 1.13497238]])

In [56]:
data[letters == 'A', 1]

array([1.46550728, 1.80359308])

In [57]:
data[letters != 'A', :1] #Selects first element of all arrays which do not represent A

array([[-1.61003213],
       [ 2.59176101],
       [-0.05762776],
       [ 0.23095509],
       [-0.74694435],
       [ 1.47312423]])

In [59]:
data[~(letters == 'A'), :1] #output will remain same

array([[-1.61003213],
       [ 2.59176101],
       [-0.05762776],
       [ 0.23095509],
       [-0.74694435],
       [ 1.47312423]])

In [60]:
#Like conditional statements we can carry multiple operations at a time using the boolean operators

AE_removed = ~(letters == 'A') & (letters != 'E')
AE_removed

array([False,  True,  True, False, False,  True, False,  True])

In [62]:
data[AE_removed] #Gives data elements in which A and E letters are not present

array([[-1.61003213, -0.86952259],
       [ 2.59176101,  1.99922177],
       [ 0.23095509, -1.33752169],
       [ 1.47312423,  0.22367995]])

In [64]:
AorE_included = (letters == 'A') | (letters == 'E')
AorE_included

array([ True, False, False,  True,  True, False,  True, False])

In [65]:
data[AorE_included] #Gives values representing either A or E

array([[-0.3441696 ,  1.46550728],
       [ 1.13497238,  1.80359308],
       [-0.05762776,  1.24240666],
       [-0.74694435, -0.04132778]])

In [67]:
#We can use indexing to change all certain values into a given value
#Suppose the condition given is that only positive values are applicable whereas all negative values are to be considered 0
#We can use the Boolean indexing for such application

data[data < 0] = 0 #Converts all negative values in data to 0
data

array([[0.        , 1.46550728],
       [0.        , 0.        ],
       [2.59176101, 1.99922177],
       [1.13497238, 1.80359308],
       [0.        , 1.24240666],
       [0.23095509, 0.        ],
       [0.        , 0.        ],
       [1.47312423, 0.22367995]])

In [70]:
#Same goes in case of rows and columns
data[~((letters == 'E') | (letters == 'B'))] = 5 #Converts all values representing neither E nor B to 5
data

array([[5.        , 5.        ],
       [0.        , 0.        ],
       [5.        , 5.        ],
       [5.        , 5.        ],
       [0.        , 1.24240666],
       [5.        , 5.        ],
       [0.        , 0.        ],
       [5.        , 5.        ]])

In [73]:
#Fancy Indexing
fancy_arr = np.empty((8,4))
for i in range(8):
    fancy_arr[i] = i
fancy_arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [74]:
#To get subset of given array in desired we can use
fancy_arr[[4,0,3,6]]

array([[4., 4., 4., 4.],
       [0., 0., 0., 0.],
       [3., 3., 3., 3.],
       [6., 6., 6., 6.]])

In [75]:
fancy_arr[[-3,4,-1]]

array([[5., 5., 5., 5.],
       [4., 4., 4., 4.],
       [7., 7., 7., 7.]])

In [76]:
fancy_arr2d = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
fancy_arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [78]:
#Applying fancy indexing on such arrays shows results as shown
fancy_arr2d[[-2,0,-3],[1,-1,2]] 
#For arr[[A],[B]] gives the (B+1)th element of the (A+1)th row

array([9, 3, 6])

In [79]:
#Transposing Arrays
#The transpose of a given ndarray can be performed using T attibute or transpose method

trans_arr = fancy_arr2d.T
trans_arr

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [80]:
arr1_3d

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 5, 5],
        [5, 5, 5]]])

In [81]:
arr1_3d.transpose((1,0,2))

array([[[1, 2, 3],
        [5, 5, 5]],

       [[3, 4, 5],
        [5, 5, 5]]])

In [90]:
#Swapping axes
#We can swap axes in an array by using swapaxes method and passing pair of axis numbers

arr1_3d.swapaxes(2,1)

array([[[1, 3],
        [2, 4],
        [3, 5]],

       [[5, 5],
        [5, 5],
        [5, 5]]])