In [2]:
#We can use statstical methods in numpy on arrays for data processing purposes

#Some of these are mentioned as under:

import numpy as np
from numpy.random import randn

data = randn(5,4)
data

array([[-0.97872554, -0.46356244,  1.3922046 , -0.96398794],
       [-0.50689651,  0.26098338, -0.65482834,  1.0093453 ],
       [-0.44440787, -2.3193851 ,  0.7040289 ,  0.08837219],
       [-1.22212494,  0.65296398, -0.03782775,  0.75681772],
       [-1.31233681,  1.2051613 ,  0.01207815,  0.56413249]])

In [3]:
#Mean value function: mean
np.mean(data)

-0.11289976128875331

In [4]:
#Additional axis argument can be given to mean, which finds means along that particular axis
np.mean(data, axis = 1)

array([-0.25351783,  0.02715096, -0.49284797,  0.03745725,  0.11725878])

In [5]:
#Summation value function: sum
np.sum(data)

-2.2579952257750664

In [6]:
#Additional axis argument can be given to sum, which finds sum along that particular axis
np.sum(data, 0)

array([-4.46449165, -0.66383889,  1.41565555,  1.45467976])

In [7]:
#Standard Deviation function: std
np.std(data)

0.9387680172117109

In [13]:
#Additional argument allows to compute standard deviation along a certain dimension
np.std(data, 1)

array([0.97252443, 0.66514769, 1.1301455 , 0.78875585, 0.92709688])

In [14]:
#Variance function: var
np.var(data)

0.8812853901396072

In [15]:
#Additional argument allows to compute variance along a particular axis
np.var(data, 0)

array([0.12836524, 1.4906378 , 0.49269024, 0.48473204])

In [16]:
#Maximum value function: max
np.max(data)

1.3922046018160443

In [17]:
#Minimum value function: min
np.min(data)

-2.3193851000495096

In [18]:
#Maximum Index Value Function: argmax
np.argmax(data)

2

In [19]:
#Minimum Index Value Function: argmin
np.argmin(data)

9

In [39]:
#Cumulative Sum function: cumsum (Starting from 0)
data2 = randn(4,3)
data2

array([[-0.08561185, -0.09479014,  1.26101276],
       [ 0.09860458, -0.87188753, -0.7315243 ],
       [ 0.24212062,  1.11690374,  1.12849184],
       [-0.06623721,  1.71512039, -0.6974301 ]])

In [40]:
np.cumsum(data2)

array([-0.08561185, -0.18040199,  1.08061077,  1.17921535,  0.30732782,
       -0.42419649, -0.18207587,  0.93482787,  2.06331971,  1.9970825 ,
        3.71220289,  3.01477279])

In [41]:
#Cumulative product: cumprod (Starting from 1)
np.cumprod(data2)

array([-8.56118494e-02,  8.11515930e-03,  1.02333194e-02,  1.00905218e-03,
       -8.79780019e-04,  6.43580464e-04,  1.55824101e-04,  1.74040521e-04,
        1.96403307e-04, -1.30092069e-05, -2.23123560e-05,  1.55613088e-05])