In [1]:
#We can also perform file input/output operations using the Numpy arrays
#Numpy allows to save and load array data on disk in text or binary format

import numpy as np

data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
#Storing Array Data on Disk as Binary Format

#Saving Data Function: save
np.save('some_data',data) #Saves data in .npy extension by default

In [3]:
#Loading Data Function: load
np.load('some_data.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#Saving Data in .Zip File Function: savez
np.savez('some_data_archieve.npz', a = data, b = data)

In [5]:
#Loading Data from .Zip File Function: load (returned object is a Dict)
archieve_data = np.load('some_data_archieve.npz')

In [6]:
archieve_data

In [7]:
#We can extract the data from this Dict by calling the key values
archieve_data['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
archieve_data['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#Saving and Loading Text Files
from numpy.random import randn

data2 = randn(4,4)
data2

array([[ 0.10325184,  1.462772  ,  0.39970187, -0.18821549],
       [-0.82959097, -1.56953916,  0.89599828, -0.38778666],
       [-0.66539946,  0.0680077 , -0.64432513, -0.06580105],
       [-1.15740344, -0.94284507, -0.35162299,  1.61787379]])

In [13]:
#Saving Data into a Text File: savetxt
np.savetxt('array_ex.txt', data2)

In [15]:
#Loading Data from a Text File: loadtxt
np.loadtxt('array_ex.txt')

array([[ 0.10325184,  1.462772  ,  0.39970187, -0.18821549],
       [-0.82959097, -1.56953916,  0.89599828, -0.38778666],
       [-0.66539946,  0.0680077 , -0.64432513, -0.06580105],
       [-1.15740344, -0.94284507, -0.35162299,  1.61787379]])