In [6]:
#Creating ndarrays
data1 = [6, 7.5, 2, 1, -5, 0] #list of floats and integers 

In [9]:
import numpy as np
arr1 = np.array(data1) #creates ndarray of floats

In [5]:
arr1 #displays array of floats

array([ 6. ,  7.5,  2. ,  1. , -5. ,  0. ])

In [8]:
data2 = [[1,2,3,4],[5,6,7,8]] #list of lists

In [12]:
arr2 = np.array(data2) #creates ndarray of given data

In [11]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr2.ndim #gives dimensions of ndarray(rows)

2

In [14]:
arr2.shape #gives order of the ndarray(rows, columns)

(2, 4)

In [15]:
arr1.dtype #gives datatype of elements in arr1

dtype('float64')

In [16]:
arr2.dtype #gives datatype of elements in arr2

dtype('int32')

In [17]:
zero_arr1 = np.zeros(10) #creates an array containing 0's

In [18]:
zero_arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
"""In case of higher ordered arrays, we pass a tuple containing 
the order of the array (row,column)"""

zero_arr2 = np.zeros((2,4)) #creates ndarray of (2,4) containing 0's

In [20]:
zero_arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
garbage_arr1 = np.empty((3,4)) #creates ndarray of (3,4) containing garbage values

In [22]:
garbage_arr1

array([[1.50692055e-312, 0.00000000e+000, 8.76794447e+252,
        2.15895723e+227],
       [6.48224638e+170, 3.67145870e+228, 7.58253645e-096,
        9.03292329e+271],
       [9.08366793e+223, 1.41075687e+232, 1.16070543e-028,
        4.05919345e-317]])

In [23]:
#In numpy, arange works like the range function and creates an ndarray out of the values
sequence_arr1 = np.arange(15) #creates an array containing values from 0 to 14

In [24]:
sequence_arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
sequence_arr2 = np.arange(13,2,-2) 

In [26]:
sequence_arr2

array([13, 11,  9,  7,  5,  3])

In [36]:
ones_arr1 = np.ones(10) #creates ndarray containing 1's

In [37]:
ones_arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
ones_arr2 = np.ones((2,3,4)) #creates ndarray of (2,3,4) containing 1's

In [39]:
ones_arr2

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [41]:
ones_arr3 = np.ones_like(sequence_arr1) #creates ndarray of 1's having shape and dtype of sequence_arr1 

In [42]:
ones_arr3

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [43]:
zeros_arr3 = np.zeros_like(sequence_arr1) #creates ndarray of 0's having shape and dtype of sequence_arr1

In [44]:
zeros_arr3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [45]:
garbage_arr3 = np.empty_like(sequence_arr1) #creates ndarrays of garbage values having shape and dtype of sequence_arr1

In [46]:
garbage_arr3

array([       162,    8388608,   81420284,          0,          0,
                0,          1,         -1,     -65535,          0,
                0,   65150448,          0, 1701734764,          0])

In [47]:
identity_arr1 = np.eye(10) #creates a identity ndarray i.e. containing 1's on leading diagonals and 0's everywhere else

In [48]:
identity_arr1

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [49]:
identity_arr2 = np.identity(10) #Same as eye ndarray

In [50]:
identity_arr2

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])