In [2]:
import numpy as np

#D-types are named with the the name of type followed by the number of bits it represents 
#Following are the different d-types mentioned below:

#int8/uint8 => Signed/Unsigned Integer(8-bits)
#int16/uint16 => Signed/Unsigned Integer(16-bits)
#int32/uint32 => Signed/Unsigned Integer(32-bits)
#int64/uint64 => Signed/Unsigned Integer(64-bits)
#float 16/32/64/128 => Floating Point(16/32/64/128 bits)
#complex 64/128/256 => Complex Number(64/128/256 bits)
#bool => Boolean number(1 bit i.e. either True or False)
#object => Python object type(Bits based on the initializing in its class)
#string_ => Fixed length string type(1 byte per character)
#unicode_ => Fixed length unicode type(Number of bytes depend upon platform)


In [6]:
#ndarrays can be type casted from one dtype to another using astype()

int_arr1 = np.array([1,2,3,4,5])
int_arr1.dtype

dtype('int32')

In [11]:
float_arr1 = int_arr1.astype(np.float64) #typecasted into float64
float_arr1

array([1., 2., 3., 4., 5.])

In [12]:
float_arr2 = np.array([2.3,4.3,5.3,1.5,6.64,6.4])
float_arr2.dtype

dtype('float64')

In [13]:
int_arr2 = float_arr2.astype(np.int32) #typecasted into int32
int_arr2

array([2, 4, 5, 1, 6, 6])

In [14]:
num_strings = np.array(['1.23','-3.4','4.234'])
num_strings

array(['1.23', '-3.4', '4.234'], dtype='<U5')

In [15]:
float_arr3 = num_strings.astype(np.float64) #typecasted into float64
float_arr3

array([ 1.23 , -3.4  ,  4.234])

In [17]:
#Type casting can also be achieved by using the dtype attribute of another array as the astype argument
int_arr3 = float_arr3.astype(int_arr2.dtype)
int_arr3

array([ 1, -3,  4])

In [19]:
#D-types can also be referred using shorthand type codes
new_arr = np.empty(8, dtype = 'u4')
new_arr

array([1550587296, 1550587232,    6554236,   74582379, 1550358752,
        160140528,  160140568,    2257486], dtype=uint32)

In [20]:
#Various shorthand type codes are as under:
#int 8/16/32/64 = i1/i2/i4/8
#uint 8/16/32/64 = u1/u2/u4/u8
#float 16/32/64/128 = f2/f4 or f/f8 or d/f16 or g
#complex 64/128/256 = c8/c16/c32
#bool = ?
#object = O
#string_ = S
#unicode_ = U