In [1]:
#Numpy can be used to generate random values for a ceratin array elements
#This generates sample values for arrays from many kinds of probability distributions

import numpy as np
import numpy.random


In [2]:
#Seeds random number generator(gives initial value to random generator to create all random values): seed
np.random.seed(1)

In [13]:
#Random sample from Uniform Distribution: rand
X = np.random.rand(10)
X

array([0.51815255, 0.86502025, 0.82914691, 0.82960336, 0.27304997,
       0.0592432 , 0.67052804, 0.59306552, 0.6716541 , 0.41178788])

In [16]:
#Random integer sample from given low to high range: randint
X2 = np.random.randint(1,11)
X2

8

In [31]:
#Random sample from Normal Distribution with mean = 0 and Std = 1: randn
X3 = np.random.randn(10)
X3

array([-0.93786433, -1.3856563 , -0.33888054, -0.17925544, -0.24094727,
       -0.24769856, -0.16851994,  0.57370922, -0.95677318, -0.65152255])

In [32]:
#Random sample from Binomial Distribution: binomial
X4 = np.random.binomial(10,0.10,100)
X4

array([3, 2, 2, 1, 0, 2, 2, 1, 1, 0, 0, 1, 0, 2, 1, 0, 2, 0, 0, 0, 0, 1,
       0, 0, 3, 1, 2, 1, 0, 1, 1, 2, 0, 1, 1, 1, 2, 1, 2, 0, 0, 2, 0, 0,
       0, 1, 2, 1, 1, 0, 1, 0, 1, 0, 1, 3, 0, 1, 0, 1, 2, 1, 0, 1, 2, 0,
       0, 3, 1, 0, 1, 0, 3, 0, 3, 0, 0, 2, 0, 2, 1, 0, 1, 0, 0, 0, 1, 1,
       2, 2, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0])

In [33]:
#Random sample from Gaussian Distribution: normal
X5 = np.random.normal(10)
X5

10.176001143769438

In [36]:
#Random sample from Beta Distribution: beta
X6 = np.random.beta(10,10)
X6

0.35084536799172106

In [37]:
#Random sample from Chi-square Distribution: chisquare
X7 = np.random.chisquare(10)
X7

7.616863289989834

In [39]:
#Random sample from Gamma Distribution: gamma
X8 = np.random.gamma(10)
X8

6.390743513572102

In [40]:
#Random sample from uniform [0,1) Distribution: uniform
X9 = np.random.uniform(10)
X9

9.910002476795643

In [45]:
#In most functions stated above, we can use the size argument to tell the size of sample we want to generate
X10 = np.random.normal(size = (4,4))
X10

array([[ 0.3743189 , -1.84955116, -0.27810508,  0.31784693],
       [-0.35876103, -0.04193944,  1.25794105,  0.62834995],
       [-1.00292632,  0.78797796, -1.05711954,  0.54215727],
       [ 0.91940949,  0.05073418,  1.20135336, -0.08601853]])

In [52]:
X11 = np.random.gamma(shape = 1 , scale = 2, size = (5,2))
X11

array([[1.96225376, 0.77559961],
       [0.09694872, 2.57011088],
       [2.84800908, 1.04277678],
       [2.43705663, 1.76068542],
       [6.98429186, 0.72446192]])

In [60]:
#Random Permutation function: permutation
X12 = np.random.permutation(X11)
X12

array([[2.84800908, 1.04277678],
       [0.09694872, 2.57011088],
       [1.96225376, 0.77559961],
       [2.43705663, 1.76068542],
       [6.98429186, 0.72446192]])

In [61]:
#Random Shuffling function: shuffle
np.random.shuffle(X11)
X11

array([[2.43705663, 1.76068542],
       [1.96225376, 0.77559961],
       [2.84800908, 1.04277678],
       [6.98429186, 0.72446192],
       [0.09694872, 2.57011088]])