In [1]:
#Like normal lists and arrays, we can sort the numpy arrays

import numpy as np
from numpy.random import randn

data = randn(8)
data

array([-1.19031956,  0.24907322,  0.22310291,  0.258528  , -0.67043178,
       -0.55656568,  0.02477061, -1.11470371])

In [3]:
#To sort elements we use: sort method
data.sort()
data

array([-1.19031956, -1.11470371, -0.67043178, -0.55656568,  0.02477061,
        0.22310291,  0.24907322,  0.258528  ])

In [16]:
#Additional argument can be given to indicate axis of sorting
data2 = randn(4,3,2)
data2

array([[[-1.81043418,  1.78743551],
        [ 0.96025698, -0.89585684],
        [-0.48086345,  0.20743589]],

       [[-0.26611516, -2.48704161],
        [-0.111711  , -0.19706951],
        [ 2.42396629, -2.42499169]],

       [[-2.0771927 , -0.09589411],
        [-0.33108127,  1.11869435],
        [-0.01051067, -2.27975407]],

       [[ 0.27260319, -1.97050397],
        [-1.70179448,  0.08759852],
        [-0.10954968, -0.64629493]]])

In [18]:
data2.sort(2)
data2

array([[[-1.81043418, -0.89585684],
        [-0.48086345,  0.20743589],
        [ 0.96025698,  1.78743551]],

       [[-2.48704161, -0.26611516],
        [-2.42499169, -0.111711  ],
        [-0.19706951,  2.42396629]],

       [[-2.27975407, -2.0771927 ],
        [-0.33108127, -0.09589411],
        [-0.01051067,  1.11869435]],

       [[-1.97050397, -1.70179448],
        [-0.64629493, -0.10954968],
        [ 0.08759852,  0.27260319]]])

In [19]:
#Using sort method we can compute quantile of an array as
large_arr = randn(1000)
large_arr

array([-7.51345418e-01,  1.20219668e+00,  2.56331780e-02, -5.39652391e-01,
        4.09102955e-02,  1.80253351e-01,  3.46459972e-01, -4.59600623e-01,
       -2.09652542e-01,  5.32062316e-01, -7.03944015e-01,  1.23147355e+00,
        7.53468435e-01, -1.57555769e+00, -7.93806402e-01, -1.90032267e-01,
       -4.73009597e-01, -3.28940736e-01, -8.84621710e-01,  6.26885868e-01,
       -2.03664144e+00,  2.15389118e-01,  1.20041639e+00, -2.60065546e-02,
        9.68647240e-01, -8.14322391e-02,  6.33126888e-01,  7.32275310e-01,
       -3.88181336e-01, -2.53694265e-01,  1.29652725e+00,  4.53705001e-01,
        1.57158959e+00,  4.72527979e-01,  3.46934514e-01,  1.85917515e+00,
       -6.82369245e-01,  7.11941439e-01,  3.63107499e-02,  7.46535213e-01,
        3.42641182e-01, -8.27134497e-01, -1.68408271e-01, -9.40337448e-01,
        1.18983609e+00, -2.18422107e-01, -1.42091019e+00, -5.15104505e-01,
        1.16602430e+00,  3.11675853e-01,  8.08221079e-01,  2.96278553e+00,
        1.33248066e+00, -

In [20]:
large_arr.sort()
large_arr

array([-3.09058481e+00, -2.98406370e+00, -2.80883338e+00, -2.74481795e+00,
       -2.68458231e+00, -2.62280123e+00, -2.60512980e+00, -2.49779171e+00,
       -2.47869274e+00, -2.44689160e+00, -2.44419245e+00, -2.43902809e+00,
       -2.42859856e+00, -2.38201578e+00, -2.30899035e+00, -2.24305677e+00,
       -2.24022758e+00, -2.22704789e+00, -2.22314281e+00, -2.18346255e+00,
       -2.18028279e+00, -2.16793709e+00, -2.14493081e+00, -2.13434665e+00,
       -2.10649470e+00, -2.08102542e+00, -2.05741885e+00, -2.05262321e+00,
       -2.03664144e+00, -2.02827329e+00, -2.01382214e+00, -1.99367702e+00,
       -1.99338302e+00, -1.90604084e+00, -1.90102016e+00, -1.87687956e+00,
       -1.86112665e+00, -1.81344182e+00, -1.80525728e+00, -1.79691015e+00,
       -1.79212522e+00, -1.77790677e+00, -1.75957473e+00, -1.75927260e+00,
       -1.74287493e+00, -1.74274486e+00, -1.70187918e+00, -1.69431174e+00,
       -1.69187463e+00, -1.68104328e+00, -1.66595914e+00, -1.65962837e+00,
       -1.64977941e+00, -

In [21]:
large_arr[int(0.05 * len(large_arr))] #5% quantile

-1.6659591444566904