In [1]:
import numpy as np

#numpy.where is vectorized form of python ternary expresssion (if else statement)

xarr = np.array([1.,2.,3.,4.,5.])
yarr = np.array([1.4,2.5,3.6,4.7,6.8])
conditions = np.array([True, False, False, True, False])

In [3]:
#Suppose we want to take value from xarr if condition is True and from yarr if condition is False

#In case of pure Python, the task can be performed via list comprehension as:
result = [(x if c else y) for x,y,c in zip(xarr,yarr,conditions)]
result

[1.0, 2.5, 3.6, 4.0, 6.8]

In [4]:
#In case of numpy, we can use where() to perform the above task as:
result = np.where(conditions, xarr, yarr)
result

array([1. , 2.5, 3.6, 4. , 6.8])

In [6]:
#Using np.where to change positive and negative values

from numpy.random import randn

data = randn(4,4)
data

array([[ 1.32969813, -1.3431948 , -1.63296197, -0.31929917],
       [-0.63439893,  0.088797  ,  0.04996672,  0.39516985],
       [ 0.00767993, -0.93328636,  0.42585378,  0.03790392],
       [ 0.67080532,  0.7480199 ,  0.26772152,  0.74426192]])

In [7]:
#Suppose we want to replace all negative values to 0 and positive to 1 then:

data = np.where(data < 0, 0, 1)
data

array([[1, 0, 0, 0],
       [0, 1, 1, 1],
       [1, 0, 1, 1],
       [1, 1, 1, 1]])

In [29]:
#Nested where expressions
#In case of two or more conditions, np.where can be nested to perform desired task

#Suppose we want values 0,1,2,3 for each of the following different conditions satisfying the value of x, then:
#conitions = [false, false], [false, true], [true, false], [true, true]

x = [-2,-1,0,1]
y = [-2,0,-1,1]

In [37]:
#Using pure Python
result_1 = []
for i in range(4):
    if (x[i] < 0) and (y[i] < 0):
        result_1.append(0)
    elif (x[i] < 0) and (y[i] >= 0):
        result_1.append(1)
    elif (x[i] >= 0) and (y[i] < 0):
        result_1.append(2)
    else:
        result_1.append(3)
        
result_1

[0, 1, 2, 3]

In [38]:
#Using np.where
result_2 = np.empty(4)
for j in range(4):
    result_2[j] = np.where((x[j] < 0) and (y[j] < 0), 0,
            np.where((x[j] < 0) and (y[j] >= 0), 1,
                    np.where((x[j] >= 0) and (y[j] < 0), 2, 3)))
result_2

array([0., 1., 2., 3.])

In [41]:
#In some cases we can apply np.where furthur to remove the for loop
#Although for this approach, we can use the 0/1 values of conditional logic to our advantage and can evaluate the values based on simple Boolean Expression

result_3 = np.empty(4)
for k in range(1, 4):
    result_3[k] = 1 * ((x[k] < 0) and (y[k] >= 0)) + 2 * ((x[k] >= 0) and (y[k] < 0)) + 3 * ((x[k] >= 0) and (y[k] >= 0))
result_3    

array([0., 1., 2., 3.])