In [1]:
#Numpy Arrays can evaluate operations of Linear Algebra
import numpy as np
from numpy.random import randn

A = np.array([[1,2,3],[4,5,6]]) #2x2 matrix
B = np.array([[1,2],[3,4],[5,6]]) #3x2 matrix

In [2]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
#Dot product function: dot
np.dot(A,B)

array([[22, 28],
       [49, 64]])

In [7]:
#Using suitable matrix, we can get 1D result from dot product of a 2D and 1D array
np.dot(A, np.ones(3))

array([ 6., 15.])

In [11]:
#Numpy gives the linalg module to perform linear algebra functionalities

import numpy.linalg

X = randn(5, 5)
X

array([[-0.92330513, -0.27545177,  1.01606084,  0.47656796, -0.25881727],
       [ 0.92064529, -1.16781398, -3.13578792, -0.40787525,  1.56836767],
       [ 0.16504961,  1.64581198,  0.78009535, -1.51762351, -1.34317362],
       [-0.75060235, -0.21383346, -0.27263813, -0.68501248, -0.85525025],
       [-1.69681292,  0.46144554, -2.47395717,  0.87598453,  1.66015274]])

In [13]:
#Diagonal Values Function: diag
np.diag(X)

array([-0.92330513, -1.16781398,  0.78009535, -0.68501248,  1.66015274])

In [14]:
#Trace Value Function: trace
np.trace(X)

-0.3358834923328249

In [15]:
#Determinant Value Function: det
np.linalg.det(X)

-7.284272432422328

In [16]:
#Eigen Value Function: eig
np.linalg.eig(X)

(array([ 2.16223833+0.j        , -1.30624168+1.75899067j,
        -1.30624168-1.75899067j,  0.89686451+0.j        ,
        -0.78250298+0.j        ]),
 array([[ 0.16685568+0.j        , -0.23207051+0.18212845j,
         -0.23207051-0.18212845j,  0.14041108+0.j        ,
         -0.35315952+0.j        ],
        [-0.43898452+0.j        ,  0.67822071+0.j        ,
          0.67822071-0.j        , -0.27583369+0.j        ,
         -0.53361388+0.j        ],
        [ 0.06005357+0.j        , -0.14210975-0.4837585j ,
         -0.14210975+0.4837585j , -0.23787721+0.j        ,
          0.20106415+0.j        ],
        [ 0.23797086+0.j        ,  0.11225518-0.16507914j,
          0.11225518+0.16507914j,  0.44685659+0.j        ,
         -0.6774018 +0.j        ],
        [-0.84806557+0.j        , -0.1785741 -0.3564136j ,
         -0.1785741 +0.3564136j , -0.80494355+0.j        ,
          0.30205063+0.j        ]]))

In [17]:
#Inverse Value Function: inv
np.linalg.inv(X)

array([[-1.14204732, -0.32262037, -0.37128838, -0.00564796, -0.17656773],
       [-0.71073733, -0.39354616,  0.11311952, -0.17575424,  0.2619634 ],
       [ 1.55309694,  0.52906657,  0.58561973, -0.74901444, -0.16974848],
       [-2.41421948, -1.29958748, -1.28384275,  0.70079412,  0.1736707 ],
       [ 2.61857842,  1.25378842,  1.1391838 , -1.44287746,  0.00447696]])

In [18]:
#Pseudo Inverse Value Function (Moore-Penrose pseudo-inverse): pinv
np.linalg.pinv(X)

array([[-1.14204732, -0.32262037, -0.37128838, -0.00564796, -0.17656773],
       [-0.71073733, -0.39354616,  0.11311952, -0.17575424,  0.2619634 ],
       [ 1.55309694,  0.52906657,  0.58561973, -0.74901444, -0.16974848],
       [-2.41421948, -1.29958748, -1.28384275,  0.70079412,  0.1736707 ],
       [ 2.61857842,  1.25378842,  1.1391838 , -1.44287746,  0.00447696]])

In [19]:
#QR Decomposition Function: qr
np.linalg.qr(X)

(array([[-0.40607308, -0.23817498,  0.41949282, -0.14740517, -0.76202023],
        [ 0.40490327, -0.47132063, -0.63571499, -0.27686549, -0.36485909],
        [ 0.07258944,  0.82710805, -0.20271468, -0.39953961, -0.33150853],
        [-0.33011775, -0.18866395,  0.04695207, -0.82275165,  0.419885  ],
        [-0.74626472,  0.03778527, -0.61367295,  0.25507851, -0.00130282]]),
 array([[ 2.27374129, -0.51529989,  0.3105706 , -0.89641647, -0.31394444],
        [ 0.        ,  2.03506339,  1.83914228, -1.01416869, -1.56442575],
        [ 0.        ,  0.        ,  3.76696051,  0.19712304, -1.89227242],
        [ 0.        ,  0.        ,  0.        ,  1.43606868,  1.26770303],
        [ 0.        ,  0.        ,  0.        ,  0.        , -0.29100531]]))

In [20]:
#SVD Decomposition Function: svd
np.linalg.svd(X)

(array([[ 1.53279987e-01,  4.29782060e-01,  1.93259855e-01,
         -3.46098645e-01, -7.96654871e-01],
        [-6.92175955e-01, -5.91557891e-01,  7.26728861e-03,
         -1.75243654e-01, -3.74417624e-01],
        [ 3.83564000e-01, -2.89961580e-01, -7.81855475e-01,
          1.83370734e-01, -3.51963251e-01],
        [ 4.98775688e-02,  4.76164759e-04, -3.26819100e-01,
         -8.89012542e-01,  3.16793274e-01],
        [-5.89736025e-01,  6.17469593e-01, -4.94458398e-01,
          1.59803830e-01,  3.02712963e-02]]),
 array([5.05640143, 2.60015677, 2.23832488, 1.27342239, 0.19437907]),
 array([[ 0.04900083,  0.22043131,  0.80509004, -0.15376595, -0.52649313],
        [-0.78356076,  0.14616422,  0.20681983,  0.54870627,  0.14427594],
        [ 0.35004857, -0.67317684,  0.3913755 ,  0.47644416,  0.21005981],
        [ 0.45909384,  0.67975922,  0.14759219,  0.29622587,  0.46650512],
        [ 0.22434416,  0.12168154, -0.36619305,  0.60044039, -0.6635038 ]]))

In [22]:
#Linear System Solution Value Function (x for Ax = b): solve
np.linalg.solve(X, np.eye(5))

array([[-1.14204732, -0.32262037, -0.37128838, -0.00564796, -0.17656773],
       [-0.71073733, -0.39354616,  0.11311952, -0.17575424,  0.2619634 ],
       [ 1.55309694,  0.52906657,  0.58561973, -0.74901444, -0.16974848],
       [-2.41421948, -1.29958748, -1.28384275,  0.70079412,  0.1736707 ],
       [ 2.61857842,  1.25378842,  1.1391838 , -1.44287746,  0.00447696]])

In [25]:
#Least Squares Solution Value Function (y for y = Xb): lstsq
np.linalg.solve(X, np.ones(5))

array([-2.01817175, -0.9049548 ,  1.74902032, -4.12318489,  3.57315015])