In [1]:
#Numpy can use basic set operations on ndarrays

import numpy as np

data = np.array(['A','B','C','B','E','A','C','C','B','A'])
data

array(['A', 'B', 'C', 'B', 'E', 'A', 'C', 'C', 'B', 'A'], dtype='<U1')

In [6]:
#Sorted unique elements function: unique
np.unique(data)

array(['A', 'B', 'C', 'E'], dtype='<U1')

In [4]:
data2 = np.array([1,2,3,2,4,5,6,4,4,3,1,5,3,6,4,2,4,6])
data2

array([1, 2, 3, 2, 4, 5, 6, 4, 4, 3, 1, 5, 3, 6, 4, 2, 4, 6])

In [5]:
np.unique(data2)

array([1, 2, 3, 4, 5, 6])

In [12]:
x = np.arange(1,8)
y = np.arange(12,4,-1)

In [13]:
x

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
y

array([12, 11, 10,  9,  8,  7,  6,  5])

In [15]:
#Sorted intersection elements function: intersect1d
np.intersect1d(x,y)

array([5, 6, 7])

In [16]:
#Sorted union elements function: union1d
np.union1d(x,y)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
#Elements indication function: in1d(x,y) indicates if elements of x are elements of y
np.in1d(x,y)

array([False, False, False, False,  True,  True,  True])

In [19]:
#Set Difference function: setdiff1d
np.setdiff1d(x,y)

array([1, 2, 3, 4])

In [20]:
#Symmetric Difference function: setxor1d
np.setxor1d(x,y)

array([ 1,  2,  3,  4,  8,  9, 10, 11, 12])