In [22]:
#Universal Functions are fast-vectorized wrappers for simple functions
#They perform fast element-wise operations on arrays

import numpy as np

int_arr = np.array([0,1,2,3,4,5])
float_arr = np.array([-3.1,-2.4,-1.5,0.,1.2,2.4,3.8,4.2,5.3])
cmplx_arr = np.array([-3+1j,-2+7j,-1+4j,0,1+2j,2+3j,3+4j,4+5j,5+6j])

In [23]:
#Unary Universal Functions

#Absolute value function: abs
np.abs(float_arr)

array([3.1, 2.4, 1.5, 0. , 1.2, 2.4, 3.8, 4.2, 5.3])

In [24]:
np.abs(cmplx_arr)

array([3.16227766, 7.28010989, 4.12310563, 0.        , 2.23606798,
       3.60555128, 5.        , 6.40312424, 7.81024968])

In [25]:
#Fast absolute function: fabs (only for non-complex)
np.fabs(float_arr)

array([3.1, 2.4, 1.5, 0. , 1.2, 2.4, 3.8, 4.2, 5.3])

In [26]:
#Square root function: sqrt
np.sqrt(int_arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [27]:
#Exponent value function: exp
np.exp(int_arr)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [28]:
#Square value function: square
np.square(int_arr)

array([ 0,  1,  4,  9, 16, 25], dtype=int32)

In [29]:
#Lograithm function: log(for base e), log10, log2
np.log(int_arr[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [30]:
#Sign value function(Finds the sign of the number): sign
np.sign(float_arr)

array([-1., -1., -1.,  0.,  1.,  1.,  1.,  1.,  1.])

In [31]:
#Ceil value function: ceil
np.ceil(float_arr)

array([-3., -2., -1.,  0.,  2.,  3.,  4.,  5.,  6.])

In [32]:
#Floor value function: floor
np.floor(float_arr)

array([-4., -3., -2.,  0.,  1.,  2.,  3.,  4.,  5.])

In [33]:
#Roundoff function: rint
np.rint(float_arr)

array([-3., -2., -2.,  0.,  1.,  2.,  4.,  4.,  5.])

In [34]:
#Modulus divider function(returns fractional and integral part seperately): modf
np.modf(float_arr)

(array([-0.1, -0.4, -0.5,  0. ,  0.2,  0.4,  0.8,  0.2,  0.3]),
 array([-3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.]))

In [38]:
#NaN checker function: isnan
np.isnan(np.sqrt(float_arr))

c:\users\mr. ghori\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


array([ True,  True,  True, False, False, False, False, False, False])

In [37]:
#Infinity checker function: isinf
np.isinf(np.log(float_arr))

c:\users\mr. ghori\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  
c:\users\mr. ghori\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log
  


array([False, False, False,  True, False, False, False, False, False])

In [39]:
#Trignometric functions: sin cos tan
np.sin(int_arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

In [40]:
#Hyperbolic functions: sinh cosh tanh
np.sinh(int_arr)

array([ 0.        ,  1.17520119,  3.62686041, 10.01787493, 27.2899172 ,
       74.20321058])

In [44]:
#Inverse trignometric functions: arcsin arccos arctan
np.arcsin(int_arr/6)

array([0.        , 0.16744808, 0.33983691, 0.52359878, 0.72972766,
       0.98511078])

In [45]:
#Inverse hyperbolic functions: arcsinh arccosh arctanh
np.arcsinh(int_arr/6)

array([0.        , 0.16590455, 0.32745015, 0.48121183, 0.62514512,
       0.75848614])

In [46]:
#Logical NOT function: logical_not
np.logical_not(int_arr)

array([ True, False, False, False, False, False])

In [63]:
#Binary Universal Functions

float_arr1 = np.array([1.2,-3.4,5.6,7.8])
float_arr2 = np.array([0.,4.,-5.4,6.3])

In [64]:
#Addition function: add
np.add(float_arr1,float_arr2)

array([ 1.2,  0.6,  0.2, 14.1])

In [65]:
#Subtraction function: subtract
np.subtract(float_arr1, float_arr2)

array([ 1.2, -7.4, 11. ,  1.5])

In [66]:
#Multiplication function: multiply
np.multiply(float_arr1, float_arr2)

array([  0.  , -13.6 , -30.24,  49.14])

In [67]:
#Division function: divide
np.divide(float_arr2, float_arr1)

array([ 0.        , -1.17647059, -0.96428571,  0.80769231])

In [68]:
#Floor division function: floor_divide
np.floor_divide(float_arr2, float_arr1)

array([ 0., -2., -1.,  0.])

In [69]:
#Power function: power
np.power(float_arr1, float_arr2)

array([1.00000000e+00, 1.33633600e+02, 9.11558729e-05, 4.17057559e+05])

In [70]:
#Maximum value function: maximum
np.maximum(float_arr1, float_arr2)

array([1.2, 4. , 5.6, 7.8])

In [71]:
#Minimum value function: minimum
np.minimum(float_arr1, float_arr2)

array([ 0. , -3.4, -5.4,  6.3])

In [72]:
#Modulus value function: mod
np.mod(float_arr2, float_arr1)

array([ 0. , -2.8,  0.2,  6.3])

In [73]:
#Copy Sign Value Function: copysign
np.copysign(float_arr1, float_arr2)

array([ 1.2,  3.4, -5.6,  7.8])

In [74]:
#Boolean comparision functions: greater greater_equal less less_equal equal not_equal
np.less_equal(float_arr1, float_arr2)

array([False,  True, False, False])

In [75]:
#Logical operators: logical_and logical_or logical_xor
np.logical_xor(float_arr1, float_arr2)

array([ True, False, False, False])